### ISSUE TITLE
Fix Nvidia proprietary drivers on Trusty device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#11]

**Comment by juhaerk** [comment]
Done. Only package nvidia-331 is installed for now.

**Comment by tuomasjjrasanen** [comment]
`VGA compatible controller: NVIDIA Corporation G73 [GeForce 7300 GT] (rev a1)`

does not seem to work with nvidia-331.38:

```
[    19.252] (WW) NVIDIA(0): The NVIDIA GeForce 7300 GT GPU installed in this system is
[    19.252] (WW) NVIDIA(0):     supported through the NVIDIA 304.xx Legacy drivers. Please
[    19.252] (WW) NVIDIA(0):     visit http://www.nvidia.com/object/unix.html for more
[    19.252] (WW) NVIDIA(0):     information.  The 331.38 NVIDIA driver will ignore this
[    19.252] (WW) NVIDIA(0):     GPU.  Continuing probe... 
```

**Comment by juhaerk** [comment]
nvidia-331 package conflicts with the nvidia-304 package that probably provides support for that particular chipset.

This can get ugly...

**Comment by juhaerk** [comment]
We are currently using nvidia-304 package that provides perhaps the best support for our current machines.

If these are some machines that do not work with nvidia-304, but need nvidia-331 or something else, please open a new ticket for those cases. Getting different nvidia-\* packages to co-operate might be tricky, but we'll see that once we know we need to do that.
