### ISSUE TITLE
Sensible update log for personal laptop

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#112]
The current update log is basically just the error log. Could this also be a full log of the past image updates. Details that might be viewable here include
- Dates of updates
- Understandable error messages and perhaps shot information what could be done to fix the issue or how to contact support.

**Comment by juhaerk** [comment]
This area has been touched by this commit: https://github.com/opinsys/puavo-ltsp/commit/7010abae94c6cf0e1183658a82346a0e4f0b1c1e. However, we do not yet show log on past image updates, and do not show information about what user could do.
