### ISSUE TITLE
Separating personal laptop update to phases

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#113]
Currently the update processon personal laptops downloads and processes the new device image based on the rdiffs in "one task". This is from the end users view point of course. Currently user doesn't not really know what is happening and cannot affect it. 

Perhaps the update process could be separeted to two different phases. Something like this:
- Laptop informs that an update is available
- User clicks the "download update" button -> this starts the download process. The user can see the progress of the download and has a possibility of cancelling it.
- When download is ready, user is informed about this and he/she can press a button to "make the update". -> This starts the creation of the new device image based on the old one and the downloaded rdiffs. Again user is informed about what is happening during this.
- When the new version has been downloaded information is shown to reboot the machine and what should be done in case the new version won't boot.

**Comment by juhaerk** [comment]
Kind of done in this commit: https://github.com/opinsys/puavo-ltsp/commit/7010abae94c6cf0e1183658a82346a0e4f0b1c1e.
