### ISSUE TITLE
Update Open Sankore to version 2.50

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#114]
http://open-sankore.org/en/download

This version will include the finnish translation so all the puppet tricks for it can be removed from the image build.

**Comment by tuomasjjrasanen** [comment]
An excerpt from the dowload page:

> A few users reported a loss of their OpenSankoré documents after installation. It's strongly
> recommended to regularly backup your documents, and mainly before install. Please contact our
> support (Feedback button, on the right) if you encounter the problem. It will help us to examine and
> solve it.

**Comment by tuomasjjrasanen** [comment]
Open-Sankore_2.5.0_i386.deb uploaded to archive
and
https://github.com/opinsys/ltsp-build/commit/1c0c6dea73dba0153bc4aadf4b4869b5888b1368
