### ISSUE TITLE
Add package rakarrack to device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#115]

**Comment by juhaerk** [comment]
Installed the package, ran the software. Complains at startup "Cannot make a jack client, is jackd running?", exits.

**Comment by juhaerk** [comment]
Whether this works or not apparently depends on a host. On "HP ProBook 430 G1" this did not work ("Cannot make a jack client, is jackd running?"), apparently jackd/alsa could not open the audio device in full duplex mode ("Cannot open PCM device als_pcm for playback. Falling back to capture-only mode"). However, on some Zotac with nvidia it starts up correctly.

**Comment by juhaerk** [comment]
I added this package: https://github.com/opinsys/ltsp-build/commit/e71d60662e7f05fea492043f719a4273ca097118. If it works at least on one type of machine, it might be useful for someone. But I did not put it into menu. Some more testing is needed if that might be reasonable. Does not work on thin clients either (at least not on the host that I tested this with).
