### ISSUE TITLE
Update Geogebra

### ISSUE THREAD

**Issue by hannele** [opinsys/puavo#119]
New version is available: http://blog.geogebra.org/2013/12/geogebra-4-4/
Geogebra gives a notification about this when it starts.

**Comment by juhaerk** [comment]
We are using the DFSG-compliant version on Trusty, and this version sits at 4.0. Moving to the 4.4 upstream version might be possible, but perhaps has legal complications.

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/opinsys-debs/commit/bec41b9542a992633a85465bbf2a4d1e119922bc
