### ISSUE TITLE
Dri problems with VIA chipset

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#120]
Devices with VIA chipset are unstable when dri is enabled. (f.ex. Epatec etc-3800). We should add a fix (tag or similar) to turn the dri on/off. It should work with all the device images (thinclient...). Currently it has been done by modifying thinclient device images like this:

```
sudo rm /usr/lib/xorg/modules/extensions/libdri.so
sudo rm /usr/lib/xorg/modules/extensions/libdri2.so
```

**Comment by tuomasjjrasanen** [comment]
How the problem is reproduced?

**Comment by asokero** [comment]
I guess running any desktop application by wine will do. For example this http://pivotanimator.net/Download

**Comment by tuomasjjrasanen** [comment]
Puavo tag -controllable mechanism for disabling 2D acceleration has been implemented: https://github.com/opinsys/puavo-ltsp/commit/7946b9a42eff819d1742e5ad635932f9b1ab4318

It is backported also to previous generation.
