### ISSUE TITLE
Lightdm respawns on thin client servers

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#121]
dmesg shows that lightdm seems to be respawning continuously on ltsp servers.

  41.606840] init: ltspguestssh main process ended, respawning
[   41.613267] init: ltspssh main process ended, respawning
[   41.628901] init: ltspguestssh main process ended, respawning
[   41.639292] init: ltspssh main process ended, respawning

[   95.925146] init: lightdm main process (5150) terminated with status 1
[   95.925157] init: lightdm main process ended, respawning
[  101.955703] init: lightdm main process (5248) terminated with status 1
[  101.955717] init: lightdm main process ended, respawning
[  107.997168] init: lightdm main process (5357) terminated with status 1

**Comment by tuomasjjrasanen** [comment]
ldm respawns too..

**Comment by tuomasjjrasanen** [comment]
https://github.com/opinsys/puavo-ltsp/commit/76bf7424f7d4ea981c256384cff625c362714fc1
and
https://github.com/opinsys/puavo-ltsp/commit/78addd707a3fb5eeb247a5b747b129fb2079dcc0
