### ISSUE TITLE
Locking user from Puavo-users doesn't work

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#124]
User accounts can be locked from the puavo-users. At the moment this feature doesn't seem to work on net boot devices. Locked users are able to log in to the desktop session.

**Comment by juhaerk** [comment]
Mostly fixed in these commits: https://github.com/opinsys/puavo-ltsp/commit/024d113d1b4100760972d7355609cb71a0a313a9, https://github.com/opinsys/puavo-users/commit/5e802b6ee6de49d629eafa8ecca488bb8fd8e2a0.

Probably some ACL-related changes are still needed for this to work, though.
