### ISSUE TITLE
Add QGis to device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#127]
Takes quite a lot of space. Is this a problem?

**Comment by tuomasjjrasanen** [comment]
Takes around 260MB of additional disk space. Not too much IMO. Squashed image size grows less of course. Decision required..

**Comment by juhaerk** [comment]
After adding qgis, compressed squashfs image size grew by 88Mb (megabytes) (in opinsysextra-image).

**Comment by juhaerk** [comment]
Added with these commits: https://github.com/opinsys/ltsp-build/commit/5728711d9f331ba0817a3ccf5c393f56e6fc4a00, https://github.com/opinsys/webmenu/commit/ef405a6dd35c1f55809fd65a2266863cc4dfdab6 and https://github.com/opinsys/ltsp-build/commit/2f0ab14b8ef077749eef1ba8dfbf8d0b33d6e687.
