### ISSUE TITLE
Occasional Firefox problems

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#128]
These might not be only Firefox related, but so far the only perceptions are with it.
- Sometimes user cannot use Ctrl+w to close tabs
- Sometimes copying information by ctrl+c from a website to does not copy the right data. Instead the clipboard might have for example the data from the location field of the browser.

These problems are hard to reproduce.

**Comment by juhaerk** [comment]
The culprit was unclutter, fixed in https://github.com/opinsys/ltsp-build/commit/f1d0365ca87a056cc2989c1d88b7f25b96967125.
