### ISSUE TITLE
Logout UI is broken after webmenu update

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#133]
This is because config.json should be updated to puppet.

{
  "passwordCMD": {
    "type": "webWindow",
    "url": "https://{{puavoDomain}}/users/password/own",
    "osIconPath": "/usr/share/icons/Faenza/emblems/96/emblem-readonly.png",
    "name": {
      "fi": "Salasana",
      "en": "Password",
      "sv": "Lösenord",
      "de": "Passwort"
      }
  },
  "shutdownCMD": {
      "type": "custom",
      "osIconPath": "/usr/share/icons/Faenza/actions/96/system-shutdown.png",
      "name": {
          "en": "Shutdown",
          "fi": "Sammuta",
          "sv": "Stäng av",
          "de": "Abscahlten"
      },
      "command": [
          "puavo-ltsp-client-action",
          "--shutdown"
      ],
      "confirm": true
  },
  "restartCMD": {
      "type": "custom",
      "osIconPath": "/usr/share/icons/Faenza/apps/96/system-restart.png",
      "name": {
          "en": "Restart",
          "fi": "Käynnistä uudelleen",
          "sv": "Starta om",
          "de": "Neustarten"
      },
      "command": [
          "puavo-ltsp-client-action",
          "--reboot"
      ],
      "confirm": true
  }
}

**Comment by juhaerk** [comment]
Fixed: https://github.com/opinsys/ltsp-build/commit/c6dfc1a0606cbb6dd6b044a2c609d11c78c2c262
