### ISSUE TITLE
Add Yle dl

### ISSUE THREAD

**Issue by hannele** [opinsys/puavo#134]
Yle dl should be added to the system.

**Comment by asokero** [comment]
http://aajanki.github.io/yle-dl/

**Comment by asokero** [comment]
Yle-dl it self is still in holld. Still rtmpdump package which is its dependency has now been added to the package lists. This means that users can now install and run yle-dl from their own home folder.
https://github.com/opinsys/puavo-rules/commit/3da75b932ff5a6d6a9046408c53f4376350e007d
