### ISSUE TITLE
USB-massstorage does not mount on thinclient

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#135]
ltspfs on /media/root/usbdisk-sda1 type fuse.ltspfs (rw,nosuid,nodev)

/dev/sda1 ext4 
/dev/sda2 extended 218 MiB
 ---->/dev/sda5 linux-swap 218 MiB

**Comment by juhaerk** [comment]
Fixed by updating /lib/udev/ltspfs_entry from the new ltspfs-version (see https://github.com/opinsys/puavo-ltsp/commit/d3ab5db856102c448a3333241c12539b6249d4d5).
