### ISSUE TITLE
Fix laptop update when booted using backup image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#140]
In case laptop has been booted using backup image this should be changed as the default image if user updates the laptop to a newer image version. Currently backup-image will be removed in image update even though the device had been booted using it and the default image might be corrupt/broken.

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/puavo-ltsp/commit/ed76d345a87c9e3c61bfca83ac5da4a373e2d956.
