### ISSUE TITLE
Display is blank on Fujitsu TX200 bootservers with Opinsys kernels

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#141]
After booting to Opinsys kernel on Fujitsu tx120 & tx200 servers display does not work. In console nothing is displayed to the user. Monitor is on and has signal. On ubuntu kernels (3.2.xxx) this is fine.

07:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. MGA G200e [Pilot] ServerEngines (SEP1) (rev 02)

**Comment by tuomasjjrasanen** [comment]
To be precise, we are not using opinsys-flavored kernels in bootservers, just mainline kernels.

**Comment by tuomasjjrasanen** [comment]
Fixed somewhere between 3.10.32 and 3.10.69. Our current kernel is 3.10.69, so the problem has been fixed.
