### ISSUE TITLE
Cleaning printer queues every night

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#142]
A script to clean print queues at bootserver cups everynight would be useful. This would ensure that at least every morning the printers would be in operation.

**Comment by tuomasjjrasanen** [comment]
Done: https://github.com/opinsys/opinsys/commit/24a6c0687208cccd8e92b3323f00e2d5c7b41770
Backported to Precise: https://github.com/opinsys/opinsys/commit/f245351f48eed61c71f9b0adadee0dcea3d5269c
