### ISSUE TITLE
Kernel messages disturb the device registration

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#143]
While registering a new device to puavo, kernel messages are occationally displayed on the same screen as the registration form. Sometimes this makes the process quite difficult if kernel is on a really talkative mood.

**Comment by tuomasjjrasanen** [comment]
Probably a well placed `dmesg -n1` or `dmesg -n2` is sufficient.

**Comment by tuomasjjrasanen** [comment]
Done: https://github.com/opinsys/puavo-ltsp/commit/f4e1e460efe740f07ba190bea68b0ab8c3d9683c
