### ISSUE TITLE
Add SimpleScreenRecorder to system

### ISSUE THREAD

**Issue by hannele** [opinsys/puavo#150]

**Comment by asokero** [comment]
https://launchpad.net/~maarten-baert/+archive/ubuntu/simplescreenrecorder/+packages

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/puavo-rules/commit/02a5b338cc614f8970ab49a9b5583d35e9e135e7, https://github.com/opinsys/puavo-rules/commit/21096f4550b89a086a7616a93ec675564c254047, https://github.com/opinsys/opinsys-debs/commit/a8ce89c67dc77046406e75afdc8215953e7ef989, https://github.com/opinsys/opinsys-debs/commit/c6ce68c8b6b3d0a76dc84a556499680787e32720.
