### ISSUE TITLE
Random issues with lightdm starting

### ISSUE THREAD

**Issue by juhaerk** [opinsys/puavo#155]
At least on one host, ASRock H61M-ITX, with "Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09)", there are issues with lightdm starting (as a fatclient). Sometimes lightdm starts in such a way that it does not show up on the screen, sometimes it does. It is perhaps fifty-fifty probability after boot.

"service lightdm restart" fixes it after it happens. "sleep 10" in /etc/init/lightdm.conf (before lightdm is started) fixes it as well.

When the issue happens, /var/log/lightdm/x-0-greeter.log shows that only one monitor is found, with 1024x768 resolution. Normally two monitors should be shown, with 1920x1080 resolution on both.

The issue can be fixed on a host-by-host basis by setting explicit xrandr settings (modes) to both outputs in Puavo.

This is in Trusty, we have not seen this issue in previous Ubuntu versions.

**Comment by asokero** [comment]
This can be reproduced sometimes with ASRock H61M-ITX / Xeon E3-1200 v2/3rd Gen Core. From the received customer feedback, we can assume that this also happens with other hardware too.

**Comment by juhaerk** [comment]
It seems that this trick fixes it: https://github.com/opinsys/opinsys-debs/commit/b43957c4751cec7e49d2002bfa1f5da74032cf17. Apparently when lightdm requests plymouth to quit, there is some race and some required resource is not always freed before lightdm tries to use it, or so it seems. Waiting for plymouth to quit before lightdm is started provides more deterministic and reliable behaviour. The downside is that the transition from plymouth splash to lightdm-screen is not totally seamless.
