### ISSUE TITLE
Add support for http://mooc.cs.helsinki.fi/

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#170]

**Comment by tuomasjjrasanen** [comment]
Seems to require awful lot of work...

I started by updating the current 7.0.1 packaging to fit 8.0.1 and there's lot of failed quilt patches and such. It is not impossible path at all, but seems quite laborious. Neither Debian nor Ubuntu has updated their netbeans for some time now..

**Comment by tuomasjjrasanen** [comment]
Of course, we could install it locally to a dir, then package the dir with /opt/netbeans8 -prefix and try it out. No idea if it would yield us a working netbeans8

**Comment by tuomasjjrasanen** [comment]
Oh well, I ended up being straightforward and dirty. I just downloaded their bundle-installer, installed it locally and packaged the resulting directory (550MB) with /opt/tmcbeans destination. It seems to work, at least I can create a Java -project and TMC-plugin seems to be active.

**Comment by tuomasjjrasanen** [comment]
Still needs a .desktop file

**Comment by tuomasjjrasanen** [comment]
Done.
