### ISSUE TITLE
New Netbeans projects can not be created in Trusty

### ISSUE THREAD

**Issue by hannele** [opinsys/puavo#171]
This works in Quantal. In Trusty when creating the project, the last step gets stuck.

**Comment by asokero** [comment]
Propably related to this: http://askubuntu.com/questions/484654/problem-with-netbeans-7-0-1-on-ubuntu-14-04

Might be a good idea to update to Netbeans 8 anyhow as it is needed also for the ticket #170.

**Comment by tuomasjjrasanen** [comment]
Done.
