### ISSUE TITLE
Elisa Viihde doesn't work with firefox/chrome

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#175]
http://elisaviihde.fi/

**Comment by tuomasjjrasanen** [comment]
I have reproduced the problem:
- Firefox (33.0+build2-0ubuntu0.14.04.1)
- Gecko mediaplayer (1.0.8-4ubuntu1)
- Flashblock (1.5.17-5+trusty.i386+master.531cf0dbc32b3c20a22e783612e968055ffb1d1e)

**Comment by tuomasjjrasanen** [comment]
The following is printed to stdout/stderr when trying to watch a record
from elisaviihde.fi:

```
NPP_New called
gecko mediaplayer v1.0.8
Window resized
Window resized
GMLIB-Message: after init: position=0.000 length=0.000 start_time=0.000 run_time=0.000 volume=0.00 player=dead media=unknown uri=
1416821073601   GMPInstallManager.simpleCheckAndInstall INFO    Last check was: 6546 seconds ago, minimum seconds: 86400
1416821073602   GMPInstallManager.simpleCheckAndInstall INFO    Will not check for updates.
```

**Comment by tuomasjjrasanen** [comment]
VLC-plugin seems to work.

**Comment by tuomasjjrasanen** [comment]
Replaced Gecko Mediaplayer with VLC Web Plugin. Also added elisaviihde.fi to flashblock whitelist.
