### ISSUE TITLE
Package Arduino Fritzing to the device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#18]
http://fritzing.org/home/

**Comment by tuomasjjrasanen** [comment]
It is already packaged in Debian, I'll just add it to the device image.

```
After this operation, 127 MB of additional disk space will be used.
```

I guess we are cool with that.

**Comment by tuomasjjrasanen** [comment]
Added to device image: https://github.com/opinsys/ltsp-build/commit/7d6135525ee4248191ad54b7ef7e2237fd20e917
