### ISSUE TITLE
HP EliteBook 8540w should not suspend while used as fatclient

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#183]
In case HP EliteBook 8540w is used as fatclient, closing the laptop lid makes it go to suspend mode. When the lid is opened it results as squashfs error. 

If a device is used as a netboot device it should not go to suspend mode in any case.

**Comment by asokero** [comment]
This also happens with Fujitsu Siemens ms2216.

**Comment by juhaerk** [comment]
Fixed in https://github.com/opinsys/puavo-rules/commit/d8f604d9690e5f4b9cec19577231236e943e53a3. Not tested with HP EliteBook, but if the issue exists on any type of machine, please re-open.
