### ISSUE TITLE
Fix login screen when guest session is enabled

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#19]
When Guest session is enabled the the normal login dialog is not displayed.

The way this should be is that both login options are displayed simultaneusly. Login by username should always be the default selection (even aften login-logout with guest session).

**Comment by juhaerk** [comment]
greeter-show-manual-login=true was needed in /etc/lightdm/lightdm.conf to get the old behaviour back.

Login by username is not yet always the default selection, looking into that one...

**Comment by juhaerk** [comment]
Now the default login is always with username + password (guest logins do not affect that).
