### ISSUE TITLE
Firefox search bar is buggy in first login

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#190]
After Firefox was updated to 34 the search bar started to act slow on first login. When user tries to type into the field the search bar gets jammed and starts flashing. This problem is relevant especially to every new user and also everytime a guest session is used.

**Comment by juhaerk** [comment]
Yep, we do not like the new Firefox search bar either: https://github.com/opinsys/puavo-rules/commit/5802656385f6f8a5a36b4b89dc71a83d21359724. See https://blog.mozilla.org/addons/2014/11/27/new-search-ui-coming-in-firefox-34/ for more opinions.
