### ISSUE TITLE
Problems with hosts logging to bootservers

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#194]
Hosts in our systems send their syslogs to bootserver under /var/log/hosts/.
On bootservers we use quite simple partition scheme where /var (and everything under it) resides on a single separate partition. Misbehaving hosts may fill the whole /var partition on the bootserver by sending there thousounds of messages in a short amount of time. This renders the whole system unusable since for example DHCP and LDAP need disk space under /var as well.

Of course this could happen with bootservers own services logging to /var/log also, but this hasn't occured this far.

Maybe some rsyslog configuration changes would help in this case like:
http://www.rsyslog.com/doc/rsconf1_repeatedmsgreduction.html
http://www.rsyslog.com/discarding-unwanted-messages/

Or should we consider a more fine-grained partition scheme.

**Comment by juhaerk** [comment]
These changes should fix these problems (at least mostly): https://github.com/opinsys/puavo-rules/commit/d3615a7f8c83a9a4672d8460da52fbdf1de4522d and https://github.com/opinsys/puavo-ltsp/commit/9e10f5595b3ab53bed0ae4c850042c9e33bacf4e.
