### ISSUE TITLE
Update Bluefish to 2.2.7

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#195]
Current 2.2.5 version has a known filebrowser (segfault) bug fixed in the newer releases. http://bluefish.openoffice.nl/index.html

**Comment by asokero** [comment]
This can be reproduced by:
- Launch Bluefish
- Set filebrowser to root
- Close the application

After these steps Bluefish will segfault on the next startup.

https://launchpad.net/ubuntu/+source/bluefish/2.2.6-1

**Comment by juhaerk** [comment]
Fixed: https://github.com/opinsys/opinsys-debs/commit/7036928afda47ffee5ed81ca63f8494c98482a58
