### ISSUE TITLE
Add support for Canon pixma mg5650 printer

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#200]
-Checkout the driver license and packaging and add it to the device image.
http://driverssupports.com/2014/09/canon-pixma-mg5650-driver-download.html

**Comment by juhaerk** [comment]
The package is not open source but distribution to third parties for specific use is ok, so we have this in our private changes: https://github.com/opinsys/opinsys/commit/29287b337068b9b5d0c576457c3b1373f3d42159.
