### ISSUE TITLE
Add Processing IDE

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#206]
Add to programming cathegory. I don't know if there is deb-packaging available but basic tgz can be found here https://processing.org/

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/opinsys-debs/commit/1c6f25e23dfec2fbcf91fc36b7392479ca8af805, https://github.com/opinsys/opinsys-debs/commit/363bfa08e9e0b27d15e1336213d060c42fa01f95, https://github.com/opinsys/opinsys-debs/commit/01008383842aecac169f07090b0848abb7b3443f, https://github.com/opinsys/opinsys-debs/commit/5d87ced08789a5a25b7f9eab5cd95e3e0ab093ec plus webmenu changes.
