### ISSUE TITLE
Connecting unknown wifi networks from lightdm

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#207]
Currently users can only join wifi networks that are defined in Puavo. Trying to connect to other available networks result an error about insufficient privileges.

**Comment by juhaerk** [comment]
Fixed in this commit: https://github.com/opinsys/puavo-rules/commit/78097401e425a5a9a371b7a6c5cfcbb56013dd85, BUT there are relevant fixup-commits after that.
