### ISSUE TITLE
device.json is missing occasionally after laptop installation

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#209]
device.json is missing occasionally after laptop installation.

This has be seen when installing ltsp-opinsysrestricted-trusty-2015-04-10-103142-i386.img via PXE. There has been earlier occurences with older images as well.

EDIT: Actually wlan.json is missing too.

**Comment by juhaerk** [comment]
This has been changed to be more strict these days (some months now): if there is such an error, installation is halted. As far as I know this has not come up again.

I can look this further once it is reproducible somehow. Might be a puavo-problem, might not... closing for now.
