### ISSUE TITLE
Add support French language support

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#215]

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/puavo-ltsp/commit/e719a3a1aa10e1af5770fb040363b3c6a9a5f40f, https://github.com/opinsys/puavo-rules/commit/c463d5c70684902d79a4ce1573ca8287612b74e7 and https://github.com/opinsys/puavo-rules/commit/6f1f0c32098b9e5e2d74799fc595015508b6aefd.
