### ISSUE TITLE
Guidance for the first login on personally administered laptops

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#219]
We need guidance for the first time personally administered laptop is used. SImple way to do this could be to use customized wallpapers with guidance texts.

Login screen:
- Connect internet
- Enter username / password

**Comment by juhaerk** [comment]
Solved. This is adjustable by tags `greeter_firstlogin_background:FILEPATH` and `desktop_background:FILEPATH` to set a special background for login screen (for the first time), and default desktop wallpaper, which allow putting informational backgrounds where necessary. See https://github.com/opinsys/puavo-ltsp/commit/325bf06a93761ab9c8acea6731ca70a1bbfe4c49 and https://github.com/opinsys/puavo-ltsp/commit/65ddca6d75e41b5dcd3d208bf0a5eb5e55c9bb61.
