### ISSUE TITLE
Keep wifi connected to joined network after login

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#220]
Example where the user uses the laptop for the first time:
- Boot laptop to login screen
- Connect to network via wifi
- Log in to desktop

After login it would be easier in sense of usability if the user would not have to connect to the same wifi again.

**Comment by juhaerk** [comment]
This is solved for the firstboot special case with this commit: https://github.com/opinsys/puavo-local-config/commit/212e279f7593dd9baee8a49a1242c1afcdbae39e
