### ISSUE TITLE
Logs on laptops can fill up the state partition

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#225]
Bad behaving processes could potentially fill the state partition with log files. In a worst case this could break the user login.

**Comment by juhaerk** [comment]
A good (but not full) solution for this is to activate logrotate, as is done in commits: https://github.com/opinsys/puavo-ltsp/commit/54e1628feba9e443de0298d0242a897d3eb9e41b and https://github.com/opinsys/puavo-ltsp/commit/2828ca1440491597b3698f7c8a370db8966ccb24.
