### ISSUE TITLE
Set primary user for personally administered laptop

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#226]
First userwho logs into a personally administered laptop should be set as the primary user for that device. If possible the user information could be sent to puavo.

**Comment by juhaerk** [comment]
Solved some time ago by some commits, most specifically this one: https://github.com/opinsys/puavo-local-config/commit/eeee0dd12d4d260ad49e32958b432d555009f176.

Information on the primary user (only the login name) is also sent to Puavo, and the primary user workaround is removed once that is verified.
