### ISSUE TITLE
Resetting personally administered latop to factory defaults

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#227]
Feature should be implemented to reset laptop to factory defaults.

**Comment by juhaerk** [comment]
There are two ways to do this currently, see commits https://github.com/opinsys/puavo-ltsp/commit/860bc3097e3537eec1aa2c388ada88e69f589549 and https://github.com/opinsys/puavo-ltsp/commit/3b5b2f3ff8cf1fe1af03fc901c645db1c61ab49f. I do not like the "puavo-reset-laptop-to-factory-defaults" way at all and generally it should not be used, but it might be handy on some situations.
