### ISSUE TITLE
Laptop settings - Changing powersave mode

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#240]
Disconnecting charger from the laptop makes it go to powersave mode. We could add a setting for it so that the user could decide the power mode when on battery.

**Comment by juhaerk** [comment]
Done some time ago: https://github.com/opinsys/puavo-local-config/commit/67a4fbdbbaf4667c6aeeb394fce00eb8deaf9bab, https://github.com/opinsys/puavo-local-config/commit/39363fe439c95e6f97883eba33e84fc361502a85, https://github.com/opinsys/puavo-local-config/commit/b53a740854fbd783eec07bf7138143b4459c56ae.
