### ISSUE TITLE
Laptop settings - Selecting automatic or manual updates 

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#241]
User should be able to select if he/she wants updates to be automatically downloaded and installed or if this should be done manually. Automatic updates should be the default to ensure that the majority of laptops would have the latest fixes and security updates. Still in case of automatic updates the user should be able to pause the update when it is running.

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/puavo-ltsp/commit/024554037977af77183ba564b2f27427e0ca4aef and https://github.com/opinsys/puavo-local-config/commit/1c626f1407a6eada385020c0bf3e4b1248b4cef2.
