### ISSUE TITLE
Add/modify logrotate settings for LTSP-servers

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#247]
Add or modify logrotate settings for LTSP-servers. Now for example /var/log/upstart/puavo-load-reporter may hit the 2GB file size limit and logging stops.

**Comment by juhaerk** [comment]
This was implemented some times ago, but it had a bug: logrotate would run only after boot, which is a problem for hosts with long uptimes.  This should have been fixed in this commit: https://github.com/opinsys/puavo-ltsp/commit/982b43c6bc66ae1ab72854903f1564cf2760f627.
