### ISSUE TITLE
Firefox 40 shows only a blank white window on old intel gfx chips

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#248]
This is possibly due to this hack made to resolve the corrupted url field on the same computers. https://github.com/opinsys/puavo-ltsp/blob/master/client/etc/X11/Xsession.d/46puavo-hardware-quirks
- http://forums.mozillazine.org/viewtopic.php?f=38&t=2955647
- https://support.mozilla.org/en-US/questions/1026156

**Comment by juhaerk** [comment]
Removed the previous hack, works: https://github.com/opinsys/puavo-ltsp/commit/3265ab4b9d1648a14ddf7848d997be41735b6375
