### ISSUE TITLE
Fix icon missing from the gnome-panel calendar

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#25]

**Comment by juhaerk** [comment]
Mmm... what icon exactly is missing and exactly where?

**Comment by juhaerk** [comment]
Depends on chosen icon-theme (could not see this on my desktop). Anyway, fixed in this commit: https://github.com/opinsys/ltsp-build/commit/97ef1d98d10379f35768cf5791e0f5aa14e2aea5
