### ISSUE TITLE
Update racket package

### ISSUE THREAD

**Issue by jpkorhonen** [opinsys/puavo#250]
Material of Koodiaapinen (http://racket.koodiaapinen.fi/index.html) needs newer version (>=6.1) of racket package. Vivid package works on the Trusty (http://packages.ubuntu.com/vivid/racket).

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/opinsys-debs/commit/29bebc7c544d25affd054273e2371a6ab9bee8c9

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/opinsys-debs/commit/29bebc7c544d25affd054273e2371a6ab9bee8c9
