### ISSUE TITLE
Ekapeli Alku is unplayable on intel q965 integrated graphics chip

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#255]
Ekapeli Alku has graphical problems on computer with intel q965 chipset. This chipset is uset on Core 2 Duo based computers. The game runs fine, but while playing the actual games the letters that should be clicked cannot be seen. There are also problem in the ingame settings screen.

The game runs fine on older (pentium 4 and i945) and newer intel chipsets. We could check out if there are any settings that could fix this (the game uses Unity 3d engine) or are the intel drivers ok?
![ekapeli-bugi](https://cloud.githubusercontent.com/assets/1162097/10252969/684f44b6-6943-11e5-8b0e-f6750f63ced2.png)

**Comment by juhaerk** [comment]
I hope this is a satisfactory fix: https://github.com/opinsys/opinsys-debs/commit/2c7578efcd0006fa31453995329c872297b6f599. The letters are shown, the game gets jerky, but remains playable (I think).

**Comment by juhaerk** [comment]
Some more information: works correctly on Ubuntu Quantal as is. The kernel used in Trusty does not matter (3.2.0, 3.13.0, 4.1.4 tested). Tried some other tricks too, but no luck. The bug is probably somewhere in the userland graphics stack, not in Unity/Ekapeli.
