### ISSUE TITLE
Wireless network settings for Network-Manager wrongly generated 

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#259]
For laptops wireless network settings for Network-Manager are generated based on settings in Puavo. These settings are located under /state/etc/NetworkManager/system-connection/
In some case these settings are not generated correctly and the uuid remains empty. These kind of settings are not used by Network-Manager.

Example of a problematic setting file:
[connection]
id=puavo-test_school
uuid=[]
type=802-11-wireless

[802-11-wireless]
ssid=test_school
mode=infrastructure
security=802-11-wireless-security

[802-11-wireless-security]
key-mgmt=wpa-psk
psk=123456789

[ipv4]
method=auto

[ipv6]
method=auto

OK version:
[connection]
id=puavo-test_school
uuid=c25bf8d8-34ef-426b-84ac-a7109d01be5b
type=802-11-wireless

[802-11-wireless]
ssid=test_school
mode=infrastructure
security=802-11-wireless-security

[802-11-wireless-security]
key-mgmt=wpa-psk
psk=123456789

[ipv4]
method=auto

[ipv6]
method=auto

Problem occurences were not regular with the same settings. Some laptops got functional settings, some not.

**Comment by juhaerk** [comment]
Fixed: https://github.com/opinsys/puavo-ltsp/commit/80f8e54474111497fbbd025b4061290a16826f78.
