### ISSUE TITLE
Personal network and printer settings are not removed from laptops

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#261]
When using a laptop marked as personal device, personally added wifi and printer settings are kept over boot. When the personal device setting is changed to false on the same laptop, these settings are still kept over boot. Other users are able to check these settings. This is probably not wanted.

Tested on ltsp-opinsysrestricted-trusty-2015-10-02-065105-i386

**Comment by juhaerk** [comment]
This is probably due to leftover settings from old image.

Currently, all users can create persistent network settings for themselves (not usable by others), and only primary user can create system-wide settings when on personally administered host. This is the intended behaviour.
