### ISSUE TITLE
Add gdisk package to bootservers

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#263]
GPT fdisk (aka gdisk) is a text-mode partitioning
 tool for that works on Globally Unique Identifier
 (GUID) Partition Table (GPT) disks, rather than
 on the more common (through 2009)
 Master Boot Record (MBR) partition tables.

**Comment by tuomasjjrasanen** [comment]
Fixed in https://github.com/opinsys/puavo-ltsp/commit/4e055ed8d750f3a2f15ed95240f00508a5aa53c8
