### ISSUE TITLE
Add support for the Zumo32U4 robot

### ISSUE THREAD

**Issue by jpkorhonen** [opinsys/puavo#268]
Install the hardware drivers for the directory: /usr/share/arduino/hardware/
Install example (Zumo32U4, Zumo32U4_opinsys) code for the directory: /usr/share/arduino/libraries

See more information: https://github.com/opinsys/ohjelmointi-opetuksessa/blob/master/zumo-32u4/install-Zumo32U4.sh

**Comment by asokero** [comment]
Done https://github.com/opinsys/opinsys/commit/b778ecfd6c1e0fc0fc6dbfda4ce994e1fcf0e810
