### ISSUE TITLE
Wake-On-LAN for hosts acting as wireless access points

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#272]
There should be an option in Puavo to activate wake-up with WOL for hosts acting as wireless access points. WOL-packets are send by bootservers, so this would need some work here and there.

**Comment by tuomasjjrasanen** [comment]
Agreed. Implemented in this commit: https://github.com/opinsys/puavo-rules/commit/172aabc1f3155c7489031f2a1dcc3333e97a027c

Any fatclient or wirelessaccesspoint having autopoweron tag, will be woken at 07:30 local time.
