### ISSUE TITLE
Dropbox is broken on 64 bit kernel

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#278]
Truing to run dropbox on a device image booted to 64bit kernel it fails to start. This is propably due to the multiarch environment where kernel is 64bit and almost all of the applications are 32bit. 

Dropbox script seems to make a check for the processor architecture and as the kernel is 64bit it tries to install the 64bit dropbox.

**Comment by juhaerk** [comment]
Fixed some time ago by tjjr.
