### ISSUE TITLE
Automatic RAID mirror setup sometimes broken in bootserver installation

### ISSUE THREAD

**Issue by juhaerk** [opinsys/puavo#285]
Automatic RAID mirror setup does not work in every situation when installing bootservers. This may be host hardware setup dependent, I do not know. I do not currently have a system on which to reproduce this.

**Comment by asokero** [comment]
This seems to be due to reusing hard drives that still might contain some old RAID magic information although they should be empty. To be sure this information is cleared, `wipefs` command could be used for wiping information on these drives.
