### ISSUE TITLE
Add appinventor

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#317]
http://appinventor.mit.edu

**Comment by asokero** [comment]
Linux package can be found here http://appinventor.mit.edu/explore/ai2/linux.html http://appinv.us/aisetup_linux_deb

Seems like it requires `android-tools-adb` package installed before device recognition works.

**Comment by asokero** [comment]
https://github.com/mit-cml/appinventor-sources

**Comment by asokero** [comment]
On newer Android devices also proper udev rules are needed. Otherwise the device can only be accessed by root. Using this udev rule file seems to help on test devices https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules. It allows users belonging to a defined group to have access with adb.

**Comment by juhaerk** [comment]
Done.
