### ISSUE TITLE
Update LibreOffice to version 5.3

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#320]
Remove Ubuntu version of Libreoffice

**Install debs inside these packages:**
```
http://download.documentfoundation.org/libreoffice/stable/5.3.0/deb/x86/LibreOffice_5.3.0_Linux_x86_deb.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.3.0/deb/x86/LibreOffice_5.3.0_Linux_x86_deb_langpack_fi.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.3.0/deb/x86/LibreOffice_5.3.0_Linux_x86_deb_langpack_sv.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.3.0/deb/x86/LibreOffice_5.3.0_Linux_x86_deb_langpack_de.tar.gz
```

**Install Voikko**
This might require editing the libreoffice-voikko package or it´s dependecies.
`cp -a /usr/lib/libreoffice/share/extensions/voikko /opt/libreoffice5.3/share/extensions`

**Comment by basilstotz** [comment]
Hello,
maybe one should add the french version too, as french is supported language in opinsysextra images.

regards 

Basil

**Comment by asokero** [comment]
Ok, french is also added. This one will be needed too: 
`http://download.documentfoundation.org/libreoffice/stable/5.3.0/deb/x86/LibreOffice_5.3.0_Linux_x86_deb_langpack_en-GB.tar.gz`

**Comment by asokero** [comment]
Following problem found
- Old libreoffice is still there on the side
- Open clip arts are missing
- Webmenu launcher typo wit Impress
- OpenOffice 5.3 has an upstream bug that causes the program to hang https://bugs.documentfoundation.org/show_bug.cgi?id=105017

**Comment by asokero** [comment]
LibreOffice 5.2.5 doesn't seem to have these issues other than that the opencliparts are missing.
Packages:
```
http://download.documentfoundation.org/libreoffice/stable/5.2.5/deb/x86/LibreOffice_5.2.5_Linux_x86_deb.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.2.5/deb/x86/LibreOffice_5.2.5_Linux_x86_deb_langpack_fi.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.2.5/deb/x86/LibreOffice_5.2.5_Linux_x86_deb_langpack_en-GB.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.2.5/deb/x86/LibreOffice_5.2.5_Linux_x86_deb_langpack_sv.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.2.5/deb/x86/LibreOffice_5.2.5_Linux_x86_deb_langpack_fr.tar.gz
http://download.documentfoundation.org/libreoffice/stable/5.2.5/deb/x86/LibreOffice_5.2.5_Linux_x86_deb_langpack_de.tar.gz
```

**Comment by asokero** [comment]
LibreOffice is/will be updated to 5.2.5. Version 5.3 seems to be unstable and translations are unfinished so too many regressions with it at the moment.
