### ISSUE TITLE
Sound devices not usable when user belongs to many schools

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#323]
When user belongs to many schools in Puavo (two or more school groups), problems using sound devices may occur. Needs more testing for more precise information.

Seen with ltsp-opinsysrestricted-trusty-2017-02-23-123243-i386.img

**Comment by cjoohs** [comment]
Reproduce:

Use import_tool in puavo and transfer a user from one school to another. The tool does not update user's primary group which should be the new school group after the operation. The old school group remains still primary and the user is just added to the new groups.

/var/log/syslog shows errors related to pulseaudio: [pulseaudio] core-util.c: Failed to create secure directory (/home/username/.config/pulse): Virheellinen argumentti

**Comment by asokero** [comment]
This should be now fixed.
