### ISSUE TITLE
Add dymo printer ppds to the device image and bootserver

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#34]
https://dymo.custhelp.com/app/answers/detail/a_id/101

**Comment by tuomasjjrasanen** [comment]
dymo-cups-drivers packaged: https://github.com/opinsys/opinsys-debs/commit/667d099b86cdd1d9032afecb2c363b9f7720c7c6
dymo-cups-drivers added to device image: https://github.com/opinsys/ltsp-build/commit/bb027d1f3a0017d5641d57664c6e244fd73411ce
dymo-cups-drivers backported to precise: https://github.com/opinsys/opinsys-debs/commit/dfb5bdb5d390ddea0c4d145893816c43742d6ec4

dymo-cups-drivers will be available to bootservers in the next bootserver release. However, it is not going to be installed automatically.
