### ISSUE TITLE
Add support for Iivari to the device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#36]

**Comment by juhaerk** [comment]
I added support to puavo-ltsp-client package for this. If a device has a tag "infotv", it will startup as an infotv, similarly as "webkiosk"-tag makes a device a webkiosk. See this commit: https://github.com/opinsys/puavo-ltsp/commit/13dd2d609062cea396ade0af2f5d26659310aa37

However, we are still missing iivari-client package that contains the iivari-kiosk program that functions as the web browser. The old iivari-client package can be installed to Trusty and it works, and the old backported pyside-\* package are no longer needed (meaning that the packages in Trusty are fine). However, we do not currently know how to build a new iivari-client package, and we would probably like to build it like our other puavo-packages.

There are still some other details to work on, most specifically turning the display on and off (or does it work already?).

**Comment by tuomasjjrasanen** [comment]
Iivari has been ported to our build system: https://github.com/opinsys/iivari/commit/a5b386f3068c4e8a2b7eeb9269cee3bb1c81159b

**Comment by juhaerk** [comment]
There may be some work to be done on this one, but testing is needed. Please open new tickets for specific issues.
