### ISSUE TITLE
Add support for Silverlight to the device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#37]
Find out if there would be any license or other problem to use this and if ok then add to device image. https://launchpad.net/pipelight

**Comment by juhaerk** [comment]
Pipelight is installed and works in some cases. Each user has to accept license for each plugin with the following command:

```
pipelight-plugin --enable silverlight
```

HOWEVER! The silverlight installer does not seem to work with nfs/cifs (fatclients and thinclients). By doing

```
mkdir -p /tmp/wine-pipelight-$USER
ln -fns /tmp/wine-pipelight-$USER ~/.wine-pipelight
```

and then letting the browser install the plugin, and then later moving /tmp/wine-pipelight-$USER to ~/.wine-pipelight can be used to work around the problem with the installer.

In addition, at least on Zotac with NVIDIA-driver http://katsomo.fi did not work.

Thus, this software/plugin behaves erratically, and can be recommended only on laptops with appropriate hardware for now.
