### ISSUE TITLE
Package and add Ambulant player to the device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#38]
http://www.ambulantplayer.org/

**Comment by tuomasjjrasanen** [comment]
Blaarhg.. not an easy task it seems. Ambulant 2.4 depends on qt3 which is not readily availabe anymore. Ambulant 2.5 depends on libswresample (which is kind of like libawresamble but it is not fully compatible. Libswresamble is not available in Ubuntu nor Debian. And ambulantplayer.org provides only 64bit builds.

**Comment by asokero** [comment]
The Ambulant player seems to have been updated to support Ubuntu 14.04 http://www.ambulantplayer.org/Download200.shtml

**Comment by asokero** [comment]
Currently not needed anymore.
