### ISSUE TITLE
Bookmarks with KDE and QT applications

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#40]
KDE and QT programs don´t support (naturally) filemanager bookmarks based on gtkbookmarks. This causes problems while trying to access the shader folders from for example kturtle or opensankore.

**Comment by juhaerk** [comment]
We do use symbolic links from home directories now, in addition to ~/.gtk-bookmarks, for remote home directory and shared directories. (Relevant merge: https://github.com/opinsys/puavo-sharedir/commit/69da3d5561f72604899052849f1ed0cd128cbffd).

**Comment by juhaerk** [comment]
Note that generating kde-bookmarks is not as nice as ~/.gtk-bookmarks, the corresponding file is in xml-format (I do not remember where it is...). But it is possible. Many qt programs seem to understand active gvfs-mounts, though, and that helps.
