### ISSUE TITLE
Firefox always wants to clean your profile

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#43]
Every time user starts Firefox it complains that it has not been used in a while. This notification won´t go away even if user does the suggested clean up.

**Comment by juhaerk** [comment]
How to reproduce?

**Comment by asokero** [comment]
From my experience I haven´t seen this on Trusty device image. In Quantal this was a typical problem. Might have been fixed by Firefox update or something else.

**Comment by juhaerk** [comment]
Closing, can not reproduce.
