### ISSUE TITLE
LoggerPro doesn´t have the required rights for usb 

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#44]
This had been implemented before but doesn´t seem to work. There seems to be atleast two different kind of devices used in schools.
- Bus 003 Device 011: ID 08f7:0001 Vernier LabPro
- Bus 001 Device 003: ID 08f7:0005 Vernier

**Comment by tuomasjjrasanen** [comment]
Added rule for Vernier LabPro to udev rules in vstdrivers package: https://github.com/opinsys/opinsys-debs/commit/f5398afdea8605d2839b2f4085fbb6cd022b3ce4
