### ISSUE TITLE
Add Swiss German as one of the language options in the system

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#48]

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/ltsp-build/commit/41b765147ccc65df13960571b6a1d7d3ea54ef5b.

True German language support may need other details, but new issues should be opened for those.

**Comment by vmlintu** [comment]
Current locale handling needs to changed from language only to ISO locales. Now we cannot separate between e.g. sv_SE/sv_FI and de_DE/de_CH. This needs to be handled at least in Puavo, puavo-ltsp-client's /etc/X11/Xsession.d/41puavo-set-locale and webmenu.

**Comment by juhaerk** [comment]
Done, really!
