### ISSUE TITLE
Resizing windows is difficult with current theme

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#51]
This was fixed in Quantal device image with customized windows manager theme.

**Comment by juhaerk** [comment]
Fixed: https://github.com/opinsys/ltsp-build/commit/8b5f24f3941d0a4ddc5f631067527d78ede24f6b (plus related changes to opinsys-theme package).

Note that the opinsys-theme -package is currently not public, so this change now depends on a package that is not public...
