### ISSUE TITLE
Keyboard setting in Puavo should set the keyboard in image

### ISSUE THREAD

**Issue by vmlintu** [opinsys/puavo#53]
There should be a keyboard layout setting in Puavo that sets the default keyboard layout on the login screen and on the desktop. User should still be able to change the keyboard layout on the desktop after logging in.

**Comment by juhaerk** [comment]
This has been implemented a while ago, the most recent relevant commit is: https://github.com/opinsys/puavo-ltsp/commit/19189fff8b0e706a5da2eba3a972a52e250e362c
