### ISSUE TITLE
Optimize login speed

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#62]
Login "feels" a bit slower on some occations on Trysty device image than in previous version. We might want some benchmark from this and optimize the login time.

**Comment by juhaerk** [comment]
I did some comparisons on boot time and login times on Quantal and Trusty. The test machine was Dell Latitude 2100, which is a bit on a slower side on laptops (running as a "laptop", not thinclient or fatclient).

Boot time:  Quantal 61 seconds, Trusty 81 seconds (33% increase).
Login time: Quantal 30 seconds, Trusty 51 seconds (70% increase).

Boot times were measured from image choice (kernel loading) to fully functional login screen.  Login times were measured from pressing enter to webmenu opening from panel.

**Comment by juhaerk** [comment]
On Dell Latitude 2100 got login time to about 22 seconds.
