### ISSUE TITLE
Remove suspend from lightdm menu for fat and thin clients

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#67]
Suspend is usable only for laptops so it should be disabled and removed from the lightdm unity greeter fro other devices that cannot support it.

**Comment by juhaerk** [comment]
Fixed in these commits: https://github.com/opinsys/puavo-ltsp/commit/9f7db1f8880560c08ad63fe924103c993676c43c, https://github.com/opinsys/puavo-ltsp/commit/041a75eb0f66ebff7c641f3d221bfe1db84aa0f6.
