### ISSUE TITLE
Cannot set Opinsys theme from Gnome control center

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#68]
In case you change the desktop theme to one of the given alternatives, you cannot revert back to the Opinsys modified Radiance theme.

**Comment by juhaerk** [comment]
Fixed in these commits: https://github.com/opinsys/opinsys-debs/commit/5bf173d4b55778bbe92e010bc542e53c4fa472ec and https://github.com/opinsys/opinsys/commit/c5c0fa84b427449f770564a3aa8aec8a01e012d1.
