### ISSUE TITLE
Installing a laptop without pxe

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#71]
Currently standard laptop installation requires a pxe netboot device. Still more and more laptops lack this feature and there is no easy way to install them as puavo laptops.

We need an alternative method to install such machines such as usb-installation or similar.

**Comment by juhaerk** [comment]
We have this feature since the "preinstaller" merge commit: https://github.com/opinsys/puavo-ltsp/commit/c48b29f3bd0ed7a35fe07ed43a1a3da5f9faec31
