### ISSUE TITLE
Add Enchanting application

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#74]
Enchanting is needed for programming the Lego Mindstorms. This should be packaged added to the image and tested.

http://enchanting.robotclub.ab.ca/tiki-index.php

**Comment by juhaerk** [comment]
Done: https://github.com/opinsys/ltsp-build/commit/341fb0147026846f07e4acdab67eb7015e7d0e74. The package is straight from upstream, and is not quite right (contains some .DS_Store files in wrong places and cannot be updated/reinstalled), but seems good enough and works. Perhaps repackaging is in order later.

**Comment by juhaerk** [comment]
Note! The robot device we have does not work with USB3 ports (USB2 are fine). Perhaps an issue with kernel (the version is 3.13.0-29-generic in Ubuntu Trusty)?
