### ISSUE TITLE
Setting xrandr for a laptop does not work

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#76]
Setting xrandr for a laptop from puavo does npt seem to work.

**Comment by juhaerk** [comment]
Fixed in these commits: https://github.com/opinsys/puavo-ltsp/commit/6acdc7e2a4837689002416e3eef9092c40e95899 and https://github.com/opinsys/puavo-users/commit/3902651d8cfb125aaa492dcf4616e71c2a13e79d.
