### ISSUE TITLE
Puavo sharedir usability and technical problems

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#80]
Current way of handling shared dirs with gtk-bookmarks is troublesome
- Qt and KDE applications don't support them
- Handling gtk-bookmarks in user directories is troublesome

On Trusty device image there seems to be a problem trying to open shared dirs from nautilus bookmarks.

Possible solutions:
- using xdg user directories pointing to a mount point at home folder

**Comment by juhaerk** [comment]
I merged some changes relating to this: https://github.com/opinsys/puavo-sharedir/commit/69da3d5561f72604899052849f1ed0cd128cbffhttps://github.com/opinsys/puavo-sharedir/commit/69da3d5561f72604899052849f1ed0cd128cbffdd, hopefully it is better now (there are links in home directories as well).
