### ISSUE TITLE
Numlock activated on first login with Thinkpad keyboard

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#81]
When using thinkpad keyboard the numlock gets activated by default on first login. This is troublesome because the keypad is located among the normal keys and while trying to type text some keys output numbers.

The numlock setting is somehow saved on users profile. After turning it off/on will define the behaviour of the following logins. Because of this it usually only appears once on normal user account as the user typically turns numlock off. 

On Guest login this is more of a problem because it naturally happens on every login.

This problem does not happen on for example with Acer eeepc 1201pn wit quite similar physical keyboard layout.

**Comment by tuomasjjrasanen** [comment]
Confirmed in Quantal. Fixed in Trusty.
