### ISSUE TITLE
Enable logging in to a laptop outside the school network

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#82]
Currently the first log in to a laptop has to be done in a network (wired or wireless) served by the organizations bootserver. This naturally causes problems when laptop is taken outside the schools network (for example home).

**Comment by juhaerk** [comment]
This has been done quite some ago. The most relevant commit on the client side was probably this one: https://github.com/opinsys/puavo-ltsp/commit/9c1375b0e0abf44a610fe2d775e806431be603ab
