### ISSUE TITLE
Persistent image overlays aka. superlaptop

### ISSUE THREAD

**Issue by tuomasjjrasanen** [opinsys/puavo#83]
Devices booting from local images should have an option to mount a persistent writable layer over the image fs. This feature is a so called superlaptop mode.

**Comment by tuomasjjrasanen** [comment]
The basic functionality is implemented here:  https://github.com/opinsys/puavo-ltsp/tree/trusty_superlaptop

It still lacks an easy way to enable/disable the feature. Currently it needs to be given as a boot argument to the kernel

**Comment by juhaerk** [comment]
I think we have this working fine.
