### ISSUE TITLE
Add Acroread to Trusty device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#9]

**Comment by juhaerk** [comment]
This should be discussed. Adobe has dropped support for 9.x line of acroreader and Linux is not a supported system on newer versions. See https://bugs.launchpad.net/ubuntu/+source/acroread/+bug/1176131

**Comment by juhaerk** [comment]
Acroread from Raring (version 9.5.5) can be installed to Trusty and it "works" (if it is okay to use it despite security issues).

**Comment by juhaerk** [comment]
Added this one :-(, but changed the default pdf-reader to okular. We can come back to this later.
