### ISSUE TITLE
Using Unity control center on Gnome flashback

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#92]
Currently we are using Unity control center on gnome flashback instead of Gnome control center. This has some small UI details that aren't suitable for our desktop such as Unity launcher settings in the screen resolution dialog.

**Comment by juhaerk** [comment]
We are using "gnome-session --session=gnome-fallback", which sets XDG_CURRENT_DESKTOP=Unity (environment variable). When this is set, gnome-control-center runs unity-control-center.

It is possible to run the original gnome-control-center by running gnome-control-center.real, but this is seriously not functional (there is only "Printers"-dialog available).

It appears the gnome-fallback -mode has some small details where the "Unity" UI leaks in. If really necessary, I think we could patch those details.

Could you specify in more detail what should be done? A separate ticket for hiding the Unity launcher settings?

**Comment by asokero** [comment]
There are following UI problems at the moment:
- Appearance settings: Launcher icon size and Behaviour tab
- Display settings: Unity specific settings (launcher location, scaling)
- User account settings

**Comment by tuomasjjrasanen** [comment]
https://github.com/opinsys/opinsys-debs/commit/e859e7b757a473d7ed6906e40f2dc8ab99e4d284 ends the 6 commits long patch series which fixes the problems
