### ISSUE TITLE
Running "ls -al" on bootserver /home is slow

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#95]
Running ls -al command on most of the bootservers takes a really long time (minutes in the worst cases).

**Comment by juhaerk** [comment]
Some issue with nss-lookups. "ls -l" is slow, "ls -n" is not.

**Comment by juhaerk** [comment]
This is mostly fixed by using nscd on bootservers (initial "ls -l" may be rather slow, but subsequent nss lookups hit the nscd cache and are much faster).
