### ISSUE TITLE
Creating local user with the same name as a primary user makes the laptop unusable

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#97]
If primary user of a laptop creates a local user with the same name using puavo-local-config-ui, the laptop becomes easily unusable. This should be prevented.

**Comment by juhaerk** [comment]
Fixed in these commits: https://github.com/opinsys/puavo-local-config/commit/c5afa94eedbe62ceaf565794985f2001fc6751fe, https://github.com/opinsys/puavo-local-config/commit/2c644ef102da9c4befa0606331e4837b2ea95e16.
