### ISSUE TITLE
Samba homedir access on laptops breaks after switching network

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#98]

**Comment by asokero** [comment]
Perhaps this could be activated by a Puavo tag.

**Comment by juhaerk** [comment]
This feature is now off by default, and can be activated with tag "use_sharedir_mounts". See https://github.com/opinsys/puavo-sharedir/commit/2744c5184849852df0a57bc524beb066b9747c2a and https://github.com/opinsys/puavo-sharedir/commit/be2540d8fb5d29bf010c5e53719639755f2d9cc7. This does not fix the original problem though.
